const PREGAME_PREVIEW_LINES = [
  'All eyes are on this highly anticipated clash.',
  'This fixture could shape the direction of their season.',
  'Both sides come into this match in strong form.',
  'There is plenty at stake tonight.',
  'The pressure is firmly on the home side.',
  'This is a real test of their title credentials.',
  'Confidence will be high after last week\'s result.',
  'They\'ll need to improve defensively to get a result here.',
  'Injuries could play a major role in the outcome.',
  'This rivalry rarely disappoints.',
  'A win here would send a statement to the rest of the league.',
  'The midfield battle could prove decisive.',
  'They\'ll look to exploit space in wide areas.',
  'Squad depth may be tested today.',
  'Recent form suggests a tight contest.',
  'The manager faces some big selection decisions.',
  'It\'s a chance for redemption after their last defeat.',
  'Momentum is firmly on their side.',
  'This is where leaders need to step up.',
  'Home advantage could be crucial.',
  'They\'ve struggled in this fixture historically.',
  'Tactical discipline will be essential.',
  'A fast start could settle early nerves.',
  'The defensive structure will be under scrutiny.',
  'This game has significant implications for the table.',
  'Expectations are high among the supporters.',
  'They\'ll need to be clinical in front of goal.',
  'It\'s a real opportunity to build consistency.',
  'The pressure is mounting as kickoff approaches.',
  'This could be a defining moment in their campaign.',
  'Their recent away record raises questions.',
  'The manager has hinted at tactical changes.',
  'Fitness levels may influence the tempo.',
  'The atmosphere is expected to be electric.',
  'They must tighten up at the back.',
  'A draw might not be enough for either side.',
  'It\'s a clash of contrasting styles.',
  'Defensive organization will be key.',
  'They\'ve shown resilience in recent weeks.',
  'This is a fixture steeped in history.',
  'The stakes couldn\'t be higher.',
  'Their attacking trio will be under the spotlight.',
  'A victory here could restore belief.',
  'Squad rotation might be necessary.',
  'This is a test of mental strength.',
  'They\'ll aim to control possession early.',
  'Recent head-to-head results favor the visitors.',
  'It\'s a must-perform scenario.',
  'Set pieces could be a decisive factor.',
  'They need a response after recent criticism.',
  'There\'s little room for error now.',
  'This is where tactical preparation matters most.',
  'The team selection will reveal their intent.',
  'Confidence is growing within the squad.',
  'Defensive lapses cannot be repeated.',
  'This is a real benchmark game.',
  'The supporters expect a strong showing.',
  'It\'s a chance to climb the table.',
  'Both managers are known for tactical flexibility.',
  'They\'ll need to match intensity from the first whistle.',
  'The spotlight will be on their captain.',
  'A strong midfield performance is required.',
  'The visitors have momentum behind them.',
  'This could be a season-defining fixture.',
  'They\'ll look to assert dominance early.',
  'Injuries have disrupted their rhythm.',
  'It\'s an opportunity to silence the critics.',
  'Tactical discipline must be maintained.',
  'They\'ve been inconsistent in recent outings.',
  'A win would provide breathing space.',
  'The defensive unit faces a stern examination.',
  'This is a clash of ambition and experience.',
  'The manager\'s approach will be closely analyzed.',
  'They must convert chances efficiently.',
  'The away side will aim to frustrate.',
  'It\'s a significant moment in their rebuild.',
  'The tempo could dictate the outcome.',
  'They\'ve shown vulnerability under pressure.',
  'This is a test of squad depth.',
  'The buildup has been intense all week.',
  'The attacking options provide real threat.',
  'They\'ll need composure in key moments.',
  'It\'s a platform to make a statement.',
  'Defensive communication will be critical.',
  'A positive start is essential.',
  'Both sides have something to prove.',
  'The manager demands a reaction.',
  'This is an opportunity to extend their run.',
  'Tactical awareness will be vital.',
  'The midfield creativity must improve.',
  'They\'re facing one of the league\'s toughest defenses.',
  'It\'s a clash that promises goals.',
  'The margin for error is slim.',
  'They\'ve prepared meticulously for this test.',
  'A disciplined display is required.',
  'The fans expect a competitive performance.',
  'The pressure of expectation looms large.',
  'This is about momentum as much as points.',
  'They must remain compact defensively.',
  'It\'s a key fixture in the race for qualification.',
  'Both teams are evenly matched on paper.',
  'It\'s an opportunity to close the gap.',
  'The manager may opt for a cautious approach.',
  'Confidence will be a major factor.',
  'They\'ll aim to exploit transitional moments.',
  'Defensive resilience will be tested.',
  'The squad looks refreshed after the break.',
  'It\'s a must-win encounter.',
  'The pressure is shifting toward the visitors.',
  'They\'ll rely on experience in big moments.',
  'A tactical surprise could be on the cards.',
  'The opening exchanges will set the tone.',
  'It\'s a battle for consistency.',
  'They must sharpen up defensively.',
  'The stakes are significant for both camps.',
  'Momentum could swing with an early goal.',
  'They\'ve improved steadily over recent weeks.',
  'This is a challenge of character.',
  'A strong bench may influence proceedings.',
  'The buildup suggests a tightly contested affair.',
  'They\'ve been formidable at home.',
  'This is a clash of philosophies.',
  'A setback here could dent confidence.',
  'They\'ll need to handle pressure intelligently.',
  'The defensive pairing faces a stern test.',
  'It\'s an opportunity to prove their progress.',
  'They must maintain concentration throughout.',
  'The match carries real significance.',
  'Both sides are chasing momentum.',
  'A disciplined midfield display is crucial.',
  'The tactical approach will define the rhythm.',
  'They\'ll aim to dictate possession.',
  'The away form has been unpredictable.',
  'It\'s a chance to gain psychological advantage.',
  'Squad cohesion will be important.',
  'They must avoid costly mistakes.',
  'The fixture has implications beyond three points.',
  'It\'s a real examination of their ambitions.',
  'The atmosphere could play a role.',
  'A positive result would ease pressure.',
  'They\'ve shown vulnerability late in games.',
  'This is a contest of fine details.',
  'The game plan must be executed precisely.',
  'It\'s a platform to build belief.',
  'They need composure under scrutiny.',
  'Defensive awareness is non-negotiable.',
  'This could be a breakthrough moment.',
  'They\'ve prepared extensively for this encounter.',
  'It\'s a test of leadership on the pitch.',
  'The early tempo will be revealing.',
  'They\'ll look to capitalize on recent momentum.',
  'The opposition presents a unique challenge.',
  'It\'s a fixture that demands focus.',
  'They must raise their intensity levels.',
  'A tactical reshuffle could surprise.',
  'It\'s an opportunity to assert authority.',
  'Defensive solidity will be paramount.',
  'They\'ve shown promise but need consistency.',
  'The midfield contest will shape the narrative.',
  'It\'s a game that could shift expectations.',
  'They must stay compact without the ball.',
  'The pressure of the table adds intrigue.',
  'It\'s a chance to respond emphatically.',
  'Their attacking options give reason for optimism.',
  'A disciplined defensive approach is expected.',
  'The manager faces tactical dilemmas.',
  'It\'s a defining week in their season.',
  'They\'ll aim to impose their style early.',
  'The balance between attack and defense is key.',
  'A positive result would signal progress.',
  'They must stay patient in possession.',
  'The intensity of the occasion is undeniable.',
  'It\'s a contest loaded with expectation.',
  'They\'ll look to exploit defensive weaknesses.',
  'The preparation has been meticulous.',
  'This is a high-pressure encounter.',
  'They\'ve struggled in similar fixtures.',
  'The challenge requires collective focus.',
  'It\'s a moment to prove their credentials.',
  'They must match physicality and discipline.',
  'A confident start could energize the crowd.',
  'The opposition\'s form cannot be ignored.',
  'It\'s a fixture that demands precision.',
  'They need cohesion across all phases.',
  'The spotlight will be unforgiving.',
  'It\'s an opportunity to rewrite the narrative.',
  'They must eliminate defensive errors.',
  'The squad appears united and focused.',
  'It\'s a critical stage of the campaign.',
  'They\'ll aim to control key areas of the pitch.',
  'A strong tactical identity is required.',
  'The pressure is shared across both benches.',
  'It\'s a platform for individual brilliance.',
  'They must rise to the occasion.',
  'The next ninety minutes could redefine their trajectory.',
  'It\'s a true test of ambition.',
  'They\'ve shown growth but now face a stern exam.',
  'A victory would reinforce belief internally.',
  'This is where preparation meets execution.',
  'Everything is set for a compelling contest.',
];

function hashSeed(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = ((hash << 5) - hash + value.charCodeAt(index)) | 0;
  }
  return hash >>> 0;
}

function createSeededRng(seed: number): () => number {
  let state = seed || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
}

export function pickPregamePreviewLines(seed: string, count = 2): string[] {
  if (PREGAME_PREVIEW_LINES.length === 0) {
    return [];
  }
  const rng = createSeededRng(hashSeed(seed));
  const pool = [...PREGAME_PREVIEW_LINES];
  for (let index = pool.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(rng() * (index + 1));
    [pool[index], pool[swapIndex]] = [pool[swapIndex], pool[index]];
  }
  return pool.slice(0, Math.max(0, Math.min(count, pool.length)));
}

export { PREGAME_PREVIEW_LINES };
