const PREVIOUS_GAME_REVIEW_LINES = [
  'It was a game defined by fine margins.',
  'The result reflected their clinical edge in front of goal.',
  'They controlled possession but lacked penetration.',
  'The turning point came just before halftime.',
  'That early goal shaped the entire contest.',
  'Defensively, they looked far more organized today.',
  'Their pressing strategy paid dividends.',
  'The midfield battle ultimately decided the outcome.',
  'They struggled to cope with the pace out wide.',
  'It was a disciplined away performance.',
  'The substitutions made a noticeable impact.',
  'Their game management in the final minutes was impressive.',
  'They failed to capitalize on key chances.',
  'The scoreline arguably flattered the visitors.',
  'It was a tale of two halves.',
  'Momentum shifted after the equalizer.',
  'The goalkeeper proved to be the difference.',
  'They showed resilience under pressure.',
  'The defensive line held firm when it mattered.',
  'Their attacking movement caused constant problems.',
  'The midfield lacked creativity in tight spaces.',
  'It was a dominant display from start to finish.',
  'The result leaves them with work to do.',
  'They looked sharper in transition.',
  'Discipline played a crucial role.',
  'The red card changed the complexion of the match.',
  'They controlled the tempo intelligently.',
  'It was a statement performance.',
  'Their finishing was decisive.',
  'They showed real character to come from behind.',
  'The defensive errors proved costly.',
  'They were second best in most duels.',
  'The wide areas were exploited effectively.',
  'The tactical setup worked to perfection.',
  'It was a deserved victory.',
  'They never truly found their rhythm.',
  'Their intensity dropped after the break.',
  'The late goal sealed a hard-fought win.',
  'They lacked urgency in the final third.',
  'The match highlighted their defensive vulnerabilities.',
  'It was a composed performance under pressure.',
  'They struggled against the high press.',
  'The full-backs played a pivotal role.',
  'It was a professional display.',
  'The draw felt like a fair result.',
  'They were punished for switching off.',
  'Their passing lacked precision at key moments.',
  'The bench provided fresh energy.',
  'They showed tactical maturity.',
  'The defensive shape remained compact throughout.',
  'They relied heavily on counterattacks.',
  'The midfield trio controlled proceedings.',
  'It was a high-tempo encounter.',
  'They defended deep and absorbed pressure well.',
  'The finishing touch was missing.',
  'It was a gritty performance.',
  'Their attacking patterns were predictable.',
  'They showed patience in possession.',
  'The clean sheet will boost confidence.',
  'It exposed areas that need improvement.',
  'They struggled to break down a low block.',
  'The physical battle was intense.',
  'Their composure made the difference.',
  'They failed to maintain consistency.',
  'The result could have gone either way.',
  'They created quality over quantity.',
  'The back line looked unsettled.',
  'It was a tactical chess match.',
  'The early momentum set the tone.',
  'They lacked cutting edge.',
  'Their defensive transitions were slow.',
  'It was a clinical counterattacking display.',
  'The midfield engine drove them forward.',
  'They were caught out of position too often.',
  'It was a measured performance.',
  'Their pressing forced key mistakes.',
  'They capitalized on defensive lapses.',
  'The wide players stretched the game effectively.',
  'It was a nervy finish.',
  'Their attacking substitutions changed the dynamic.',
  'The set pieces proved decisive.',
  'They looked vulnerable from crosses.',
  'It was a well-earned point.',
  'The game lacked clear-cut chances.',
  'They defended with determination.',
  'The quality in the final third stood out.',
  'It was a frustrating afternoon for them.',
  'Their build-up play was methodical.',
  'The midfield lacked balance.',
  'They adapted well after going behind.',
  'The defensive partnership looked solid.',
  'It was an entertaining contest.',
  'They lacked cohesion at times.',
  'The pressing intensity faded late on.',
  'They made their dominance count.',
  'The equalizer was fully deserved.',
  'Their energy levels were impressive.',
  'The tactical adjustments paid off.',
  'They struggled to impose themselves.',
  'It was a confidence-boosting win.',
  'The defense was tested repeatedly.',
  'They showed composure in possession.',
  'It was a balanced performance.',
  'They lacked control in midfield.',
  'The finishing was ruthless.',
  'They were exposed on the counter.',
  'It was a disciplined defensive display.',
  'The manager\'s game plan worked.',
  'They struggled with defensive organization.',
  'The atmosphere added intensity.',
  'It was a cagey affair.',
  'Their defensive discipline was commendable.',
  'The attack lacked fluidity.',
  'It was a hard-fought draw.',
  'The goalkeeper made crucial interventions.',
  'They showed mental strength.',
  'The game opened up late on.',
  'It was a composed second-half showing.',
  'They created space intelligently.',
  'The defensive lapses were punished.',
  'It was a dominant midfield display.',
  'Their wide play lacked consistency.',
  'The pressing disrupted their rhythm.',
  'It was a narrow but deserved win.',
  'They looked dangerous from set plays.',
  'The defensive block was difficult to break.',
  'It was a competitive encounter.',
  'Their movement off the ball impressed.',
  'The tempo suited their style.',
  'They failed to capitalize on possession.',
  'It was a dramatic finish.',
  'Their defensive resilience stood out.',
  'The attacking trio combined well.',
  'It was a tactical masterclass.',
  'They lacked decisiveness in key moments.',
  'The win keeps their momentum alive.',
  'Their defensive line was caught high.',
  'It was a performance full of intent.',
  'They were clinical when it mattered.',
  'The midfield struggled to dictate play.',
  'It was a nervy but important victory.',
  'Their structure without the ball was solid.',
  'The opposition dictated large spells.',
  'It was a game of patience.',
  'They missed an opportunity to extend their lead.',
  'The defensive errors overshadowed positives.',
  'It was a well-executed game plan.',
  'Their pressing created sustained pressure.',
  'The result reflects their improvement.',
  'They showed courage in possession.',
  'It was a performance built on discipline.',
  'Their lack of depth showed late on.',
  'The defensive substitutions secured the win.',
  'It was an evenly matched contest.',
  'They managed the closing stages well.',
  'The attacking transitions were sharp.',
  'It was a breakthrough performance.',
  'Their defensive concentration never wavered.',
  'The midfield controlled the narrative.',
  'It was a game of small details.',
  'They capitalized on key moments.',
  'The defensive frailties remain a concern.',
  'It was a positive response to recent setbacks.',
  'Their attacking width stretched the defense.',
  'The lack of finishing quality proved costly.',
  'It was a tactically disciplined display.',
  'They absorbed pressure effectively.',
  'The final ball often let them down.',
  'It was a much-needed win.',
  'Their defensive shape improved after halftime.',
  'The tempo dropped in the second half.',
  'It was a confidence-building result.',
  'They struggled to cope with intensity.',
  'The set-piece routines were effective.',
  'It was a professional away win.',
  'Their inability to hold possession hurt them.',
  'The defensive organization was impressive.',
  'It was a resilient performance.',
  'They dictated play for long stretches.',
  'The defensive errors were avoidable.',
  'It was a controlled and calculated display.',
  'Their attacking threat remained constant.',
  'The midfield battle was decisive.',
  'It was a statement result.',
  'They lacked a cutting edge.',
  'The defensive effort was collective.',
  'It was a tactical adjustment that swung the game.',
  'Their second-half response was key.',
  'The result underlines their consistency.',
  'It was a disappointing outing.',
  'They showed real determination.',
  'The defensive unit worked cohesively.',
  'It was an efficient performance.',
  'Their inability to convert chances cost them.',
  'The late surge nearly paid off.',
  'It was a composed and mature display.',
  'They controlled key phases.',
  'The defensive solidity proved decisive.',
  'It was a hard lesson learned.',
  'The result reflects the balance of play.',
];

function hashSeed(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = ((hash << 5) - hash + value.charCodeAt(index)) | 0;
  }
  return hash >>> 0;
}

function createSeededRng(seed: number): () => number {
  let state = seed || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
}

export function pickRecapReviewLines(seed: string, count = 2): string[] {
  if (PREVIOUS_GAME_REVIEW_LINES.length === 0) {
    return [];
  }
  const rng = createSeededRng(hashSeed(seed));
  const pool = [...PREVIOUS_GAME_REVIEW_LINES];
  for (let index = pool.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(rng() * (index + 1));
    [pool[index], pool[swapIndex]] = [pool[swapIndex], pool[index]];
  }
  return pool.slice(0, Math.max(0, Math.min(count, pool.length)));
}

export { PREVIOUS_GAME_REVIEW_LINES };
