import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useLocation } from 'react-router-dom';
import { api } from '../lib/api';

const GAMEWEEKS = ['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8'];

type Scoreboard = Awaited<ReturnType<typeof api.predictionScoreboard>>;
type PredictionResponse = Awaited<ReturnType<typeof api.predictions>>;
type Prediction = PredictionResponse['predictions'][number];
type H2H = Awaited<ReturnType<typeof api.headToHeadAllTime>>;

type FixtureInfo = { key:string; label:string; homeTeam:string; awayTeam:string; result:'home'|'away'|'draw'|'pending' };
type ResultRow = FixtureInfo & { jayPick:string; computerPick:string; jayCorrect:boolean; computerCorrect:boolean };
type SeasonChampion = { season:string; winner:string; points:number; runnerUp:string; runnerUpPoints:number };
type BroadcastData = { season:string; previousSeason:string; previousGw:string; currentScoreboard:Scoreboard; previousScoreboard:Scoreboard|null; previousRows:ResultRow[]; currentPredictions:PredictionResponse; currentFixtureLabels:Map<string,string>; champions:SeasonChampion[]; h2hSpotlight:{fixture:FixtureInfo;h2h:H2H}|null };
type Slide = { id:string; kicker:string; title:string; subtitle?:string; content:React.ReactNode; tone?:'gold'|'blue'|'red'|'green' };

function seasonNumber(season:string){const value=Number(season.replace(/\D/g,''));return Number.isFinite(value)?value:1}
function pickLabel(row:Prediction|undefined){if(!row)return '—';return row.pickOutcome==='draw'?'Draw':row.pickTeamName}
function actualWinner(info:FixtureInfo){if(info.result==='draw')return 'Draw';if(info.result==='home')return info.homeTeam;if(info.result==='away')return info.awayTeam;return 'Pending'}
function isCorrect(row:Prediction|undefined,info:FixtureInfo){if(!row||info.result==='pending')return false;if(row.pickOutcome==='draw')return info.result==='draw';return row.pickTeamName===actualWinner(info)}

async function fixtureMap(season:string,gw:string):Promise<Map<string,FixtureInfo>>{
 const [league,cup,master,masterCup,trio,tier]=await Promise.all([
  api.leagueFixtures(gw,false,season).catch(()=>[]),api.cup(gw,season).catch(()=>[]),api.masterLeagueFixtures(gw,false,season).catch(()=>[]),api.masterCupFixtures(gw,false,season).catch(()=>[]),api.trioLeagueFixtures(gw,false,season).catch(()=>[]),api.tierLeagueFixtures(gw,false,season).catch(()=>[]),
 ]);
 const map=new Map<string,FixtureInfo>();
 league.forEach(f=>map.set(`league-${f.id}`,{key:`league-${f.id}`,label:`League · ${f.division}`,homeTeam:f.homeTeam,awayTeam:f.awayTeam,result:f.result}));
 cup.forEach(f=>{if(!f.homeTeam||!f.awayTeam)return;const result:FixtureInfo['result']=!f.winnerTeam?'pending':f.winnerTeam===f.homeTeam?'home':f.winnerTeam===f.awayTeam?'away':'pending';map.set(`cup-${f.id}`,{key:`cup-${f.id}`,label:`BookieBall Cup · ${f.roundName}`,homeTeam:f.homeTeam,awayTeam:f.awayTeam,result})});
 master.forEach(f=>map.set(`master-${f.id}`,{key:`master-${f.id}`,label:'Master League',homeTeam:f.homeTeam,awayTeam:f.awayTeam,result:f.result}));
 masterCup.forEach(f=>{if(!f.homeTeam||!f.awayTeam)return;const result:FixtureInfo['result']=!f.winnerTeam?'pending':f.winnerTeam===f.homeTeam?'home':f.winnerTeam===f.awayTeam?'away':'pending';map.set(`master_cup-${f.id}`,{key:`master_cup-${f.id}`,label:`Master Cup · ${f.roundName}`,homeTeam:f.homeTeam,awayTeam:f.awayTeam,result})});
 trio.forEach(f=>map.set(`trio-${f.id}`,{key:`trio-${f.id}`,label:`Trio League · ${f.division}`,homeTeam:f.homeTeam,awayTeam:f.awayTeam,result:f.result}));
 tier.forEach(f=>map.set(`tier-${f.id}`,{key:`tier-${f.id}`,label:`Tier League · ${f.division}`,homeTeam:f.homeTeam,awayTeam:f.awayTeam,result:f.result}));return map;
}
function weekWinner(scoreboard:Scoreboard,gw:string):'Jay'|'Computer'|'Draw'|null{const rows=scoreboard.weeks.filter(r=>r.gw===gw),jay=rows.find(r=>r.picker==='Jay'),computer=rows.find(r=>r.picker==='Computer');if(!jay||!computer)return null;if(jay.points===computer.points)return'Draw';return jay.points>computer.points?'Jay':'Computer'}
function form(scoreboard:Scoreboard,picker:'Jay'|'Computer'):Array<'W'|'D'|'L'>{return GAMEWEEKS.map(gw=>weekWinner(scoreboard,gw)).filter((w):w is 'Jay'|'Computer'|'Draw'=>Boolean(w)).slice(-5).map(w=>w==='Draw'?'D':w===picker?'W':'L')}
function streak(scoreboard:Scoreboard){const winners=GAMEWEEKS.map(gw=>weekWinner(scoreboard,gw)).filter((w):w is 'Jay'|'Computer'|'Draw'=>Boolean(w));if(!winners.length)return null;const last=winners[winners.length-1];if(last==='Draw')return{winner:'Honours even',count:1};let count=0;for(let i=winners.length-1;i>=0&&winners[i]===last;i--)count++;return{winner:last,count}}
function FormDots({values}:{values:Array<'W'|'D'|'L'>}){return <div className="prediction-form-dots">{values.map((v,i)=><span key={`${v}-${i}`} className={v.toLowerCase()}>{v}</span>)}</div>}

function PredictionMiniShow({data}:{data:BroadcastData}){
 const [index,setIndex]=useState(0),totals=new Map(data.currentScoreboard.totals.map(r=>[r.picker,r]));
 const jayTotal=totals.get('Jay')??{picker:'Jay',points:0,correct:0,total:0,perfectWeeks:0},computerTotal=totals.get('Computer')??{picker:'Computer',points:0,correct:0,total:0,perfectWeeks:0};
 const previousWeeks=data.previousScoreboard?.weeks??[],prevJay=previousWeeks.find(r=>r.gw===data.previousGw&&r.picker==='Jay'),prevComputer=previousWeeks.find(r=>r.gw===data.previousGw&&r.picker==='Computer');
 const previousWinner=!prevJay||!prevComputer?'No result':prevJay.points===prevComputer.points?'Draw':prevJay.points>prevComputer.points?'Jay':'Computer';
 const currentByKey=new Map<string,Record<string,Prediction>>();data.currentPredictions.predictions.forEach(r=>{const k=`${r.competition}-${r.fixtureId}`,s=currentByKey.get(k)??{};s[r.picker]=r;currentByKey.set(k,s)});
 const comparisons=data.currentPredictions.slate.map(r=>{const k=`${r.competition}-${r.fixtureId}`,p=currentByKey.get(k)??{};return{key:k,fixture:data.currentFixtureLabels.get(k)??`Fixture ${r.fixtureId}`,jay:pickLabel(p.Jay),computer:pickLabel(p.Computer)}}).filter(r=>r.jay!=='—'&&r.computer!=='—');
 const disagreements=comparisons.filter(r=>r.jay!==r.computer),agreements=comparisons.filter(r=>r.jay===r.computer),lastWeekAgreements=data.previousRows.filter(r=>r.jayPick===r.computerPick&&r.jayPick!=='—'),agreementCorrect=lastWeekAgreements.filter(r=>r.jayCorrect&&r.computerCorrect).length,agreementRate=lastWeekAgreements.length?Math.round(agreementCorrect/lastWeekAgreements.length*100):0,currentStreak=streak(data.currentScoreboard),jayForm=form(data.currentScoreboard,'Jay'),computerForm=form(data.currentScoreboard,'Computer');
 const slides:Slide[]=[
 {id:'last-week',kicker:'LAST WEEK · FINAL SCORE',title:`${prevJay?.points??0} — ${prevComputer?.points??0}`,subtitle:previousWinner==='Draw'?'Jay and Computer finished level':`${previousWinner} won the prediction round`,tone:previousWinner==='Jay'?'gold':previousWinner==='Computer'?'blue':'green',content:<div className="prediction-versus"><div><span>JAY</span><strong>{prevJay?.correct??0}/{prevJay?.total??0}</strong><small>correct</small></div><b>VS</b><div><span>COMPUTER</span><strong>{prevComputer?.correct??0}/{prevComputer?.total??0}</strong><small>correct</small></div></div>},
 {id:'championship',kicker:'THE PREDICTION RACE',title:`${jayTotal.points} — ${computerTotal.points}`,subtitle:`${data.season} championship · ${Math.abs(jayTotal.points-computerTotal.points)} point gap`,tone:'gold',content:<div className="prediction-stat-grid"><div><span>Jay</span><strong>{jayTotal.points}</strong><small>{jayTotal.correct}/{jayTotal.total} correct · {jayTotal.perfectWeeks} perfect weeks</small></div><div><span>Computer</span><strong>{computerTotal.points}</strong><small>{computerTotal.correct}/{computerTotal.total} correct · {computerTotal.perfectWeeks} perfect weeks</small></div></div>},
 {id:'champions',kicker:'HALL OF CHAMPIONS',title:'Previous Prediction Champions',subtitle:'Recent season winners from the BookieBall archive',tone:'gold',content:<div className="prediction-champions">{data.champions.length?data.champions.slice().reverse().map(r=><div key={r.season}><span>{r.season}</span><strong>🏆 {r.winner}</strong><b>{r.points} pts</b><small>{r.runnerUp} {r.runnerUpPoints}</small></div>):<p>Historical prediction titles will appear as completed seasons are found.</p>}</div>},
 {id:'streak',kicker:'FORM WATCH',title:currentStreak?`${currentStreak.winner}${currentStreak.winner==='Honours even'?'':` · ${currentStreak.count} straight`}`:'Season just getting started',subtitle:'Weekly prediction-round momentum',tone:'red',content:<div className="prediction-form-board"><div><strong>JAY</strong><FormDots values={jayForm}/></div><div><strong>COMPUTER</strong><FormDots values={computerForm}/></div></div>},
 ...(data.h2hSpotlight?[{id:'h2h',kicker:'LAST WEEK · HEAD TO HEAD',title:`${data.h2hSpotlight.fixture.homeTeam} vs ${data.h2hSpotlight.fixture.awayTeam}`,subtitle:`${data.h2hSpotlight.h2h.played} all-time meetings`,tone:'blue' as const,content:<div className="prediction-h2h"><div><strong>{data.h2hSpotlight.h2h.teamA.name}</strong><span>{data.h2hSpotlight.h2h.teamAWins} wins</span></div><b>{data.h2hSpotlight.h2h.teamAWins} — {data.h2hSpotlight.h2h.draws} — {data.h2hSpotlight.h2h.teamBWins}</b><div><strong>{data.h2hSpotlight.h2h.teamB.name}</strong><span>{data.h2hSpotlight.h2h.teamBWins} wins</span></div></div>}]:[]),
 {id:'split',kicker:'YOU VS THE MACHINE',title:disagreements.length?`${disagreements.length} split calls this week`:'No split calls yet',subtitle:'Where Jay and Computer disagree',tone:'red',content:<div className="prediction-splits">{disagreements.slice(0,4).map(r=><div key={r.key}><span>{r.fixture}</span><strong>{r.jay}</strong><em>VS</em><strong>{r.computer}</strong></div>)}</div>},
 {id:'agreement',kicker:'WHEN YOU BOTH AGREE',title:`${agreementRate}% hit rate last week`,subtitle:`${agreementCorrect} of ${lastWeekAgreements.length} unanimous calls landed · ${agreements.length} unanimous calls this week`,tone:'green',content:<div className="prediction-agreement"><strong>{agreements.length}</strong><span>same picks on the current slate</span></div>},
 ];
 useEffect(()=>{if(slides.length<2)return;const timer=window.setInterval(()=>setIndex(v=>(v+1)%slides.length),5600);return()=>window.clearInterval(timer)},[slides.length]);
 useEffect(()=>{if(index>=slides.length)setIndex(0)},[index,slides.length]);const active=slides[index]??slides[0];if(!active)return null;
 return <section className={`prediction-mini-show tone-${active.tone??'blue'}`}><div className="prediction-mini-show-top"><div><span>{active.kicker}</span><h2>{active.title}</h2>{active.subtitle&&<p>{active.subtitle}</p>}</div><div className="prediction-mini-controls"><button type="button" onClick={()=>setIndex((index-1+slides.length)%slides.length)}>←</button><span>{index+1}/{slides.length}</span><button type="button" onClick={()=>setIndex((index+1)%slides.length)}>→</button></div></div><div key={active.id} className="prediction-mini-stage">{active.content}</div></section>
}
function LockedPicksDrama({data}:{data:BroadcastData}){const byKey=new Map<string,Record<string,Prediction>>();data.currentPredictions.predictions.forEach(r=>{const k=`${r.competition}-${r.fixtureId}`,s=byKey.get(k)??{};s[r.picker]=r;byKey.set(k,s)});const rows=data.currentPredictions.slate.map(e=>{const k=`${e.competition}-${e.fixtureId}`,p=byKey.get(k)??{};return{key:k,fixture:data.currentFixtureLabels.get(k)??`Fixture ${e.fixtureId}`,jay:pickLabel(p.Jay),computer:pickLabel(p.Computer)}}).filter(r=>r.jay!=='—'&&r.computer!=='—');if(!rows.length)return null;const disagreements=rows.filter(r=>r.jay!==r.computer);return <section className="prediction-locked-drama"><div><span>PICKS LOCKED</span><strong>{disagreements.length?'YOU VS THE MACHINE':'UNANIMOUS CARD'}</strong><small>{disagreements.length} split calls · {rows.length-disagreements.length} agreements</small></div>{disagreements.slice(0,2).map(r=><article key={r.key}><small>{r.fixture}</small><b>{r.jay}</b><em>VS</em><b>{r.computer}</b></article>)}</section>}

async function buildBroadcastData():Promise<BroadcastData>{
 const state=await api.state(),previous=await api.lastCompletedGameweek().catch(()=>({currentSeason:state.currentSeason,currentGw:state.currentGw,lastCompleted:null})),previousSeason=previous.lastCompleted?.season??state.currentSeason,previousGw=previous.lastCompleted?.gw??'';
 const [currentScoreboard,currentPredictions,currentFixtures,previousScoreboard,previousPredictions,previousFixtures,teams]=await Promise.all([api.predictionScoreboard(state.currentSeason).catch(()=>({totals:[],weeks:[]})),api.predictions(state.currentGw,state.currentSeason).catch(()=>({season:state.currentSeason,gw:state.currentGw,locked:false,slate:[],predictions:[]})),fixtureMap(state.currentSeason,state.currentGw),previousGw?api.predictionScoreboard(previousSeason).catch(()=>null):Promise.resolve(null),previousGw?api.predictions(previousGw,previousSeason).catch(()=>({season:previousSeason,gw:previousGw,locked:true,slate:[],predictions:[]})):Promise.resolve({season:previousSeason,gw:previousGw,locked:true,slate:[],predictions:[]}),previousGw?fixtureMap(previousSeason,previousGw):Promise.resolve(new Map<string,FixtureInfo>()),api.teams().catch(()=>[])]);
 const previousByKey=new Map<string,Record<string,Prediction>>();previousPredictions.predictions.forEach(r=>{const k=`${r.competition}-${r.fixtureId}`,s=previousByKey.get(k)??{};s[r.picker]=r;previousByKey.set(k,s)});const previousRows=previousPredictions.slate.map(e=>{const k=`${e.competition}-${e.fixtureId}`,fixture=previousFixtures.get(k);if(!fixture)return null;const p=previousByKey.get(k)??{};return{...fixture,jayPick:pickLabel(p.Jay),computerPick:pickLabel(p.Computer),jayCorrect:isCorrect(p.Jay,fixture),computerCorrect:isCorrect(p.Computer,fixture)}}).filter((r):r is ResultRow=>Boolean(r));
 const currentFixtureLabels=new Map<string,string>();currentFixtures.forEach((f,k)=>currentFixtureLabels.set(k,`${f.homeTeam} vs ${f.awayTeam}`));
 /* Only load the five most recent completed season scoreboards. The old version fired every season plus ten H2H requests at page startup. */
 const currentNo=seasonNumber(state.currentSeason),first=Math.max(1,currentNo-5),seasonIds=Array.from({length:Math.max(0,currentNo-first)},(_,i)=>`S${first+i}`),championScoreboards=await Promise.all(seasonIds.map(season=>api.predictionScoreboard(season).then(scoreboard=>({season,scoreboard})).catch(()=>null)));
 const champions=championScoreboards.filter((r):r is {season:string;scoreboard:Scoreboard}=>Boolean(r&&r.scoreboard.totals.length)).map(({season,scoreboard})=>{const ranked=scoreboard.totals.slice().sort((a,b)=>b.points-a.points||b.correct-a.correct||a.picker.localeCompare(b.picker));return{season,winner:ranked[0]?.picker??'—',points:ranked[0]?.points??0,runnerUp:ranked[1]?.picker??'—',runnerUpPoints:ranked[1]?.points??0}});
 const teamByName=new Map(teams.map(team=>[team.name.toLowerCase(),team]));let h2hSpotlight:BroadcastData['h2hSpotlight']=null;const fixture=previousRows.find(f=>teamByName.has(f.homeTeam.toLowerCase())&&teamByName.has(f.awayTeam.toLowerCase()));if(fixture){const home=teamByName.get(fixture.homeTeam.toLowerCase())!,away=teamByName.get(fixture.awayTeam.toLowerCase())!,h2h=await api.headToHeadAllTime(home.id,away.id).catch(()=>null);if(h2h)h2hSpotlight={fixture,h2h}}
 return{season:state.currentSeason,previousSeason,previousGw,currentScoreboard,previousScoreboard,previousRows,currentPredictions,currentFixtureLabels,champions,h2hSpotlight};
}

export function PredictionBroadcastEnhancements(){
 const location=useLocation();const[data,setData]=useState<BroadcastData|null>(null),[resultsTarget,setResultsTarget]=useState<Element|null>(null),[picksTarget,setPicksTarget]=useState<Element|null>(null);
 useEffect(()=>{if(location.pathname!=='/gameshow'){setResultsTarget(null);setPicksTarget(null);return}const sync=()=>{setResultsTarget(document.querySelector('.kickoff-flow-shell-results .kickoff-grid-results'));setPicksTarget(document.querySelector('.kickoff-flow-shell:not(.kickoff-flow-shell-results) .kickoff-grid-picks'))};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[location.pathname]);
 /* Heavy archive calls are now demand-driven: nothing extra runs while changing gameweek or making picks. */
 useEffect(()=>{if(location.pathname!=='/gameshow'||!resultsTarget||data)return;let active=true;const timer=window.setTimeout(()=>{void buildBroadcastData().then(payload=>{if(active)setData(payload)}).catch(()=>{if(active)setData(null)})},1800);return()=>{active=false;window.clearTimeout(timer)}},[location.pathname,resultsTarget,data]);
 if(!data)return null;return <>{resultsTarget?createPortal(<PredictionMiniShow data={data}/>,resultsTarget):null}{picksTarget&&data.currentPredictions.locked?createPortal(<LockedPicksDrama data={data}/>,picksTarget):null}</>;
}
